### PR TITLE
Rewrite `mkfs` in Rust

### PR DESCRIPTION
**Pull request by msrd0**
This PR is a near 1 to 1 rewrite of mkfs in Rust, except unused code removed. If desired, I can incorporate the fix to write a zero'ed index block from my other PR against the C version into this PR as well.

### CODE REVIEW

**Comment by rgouicem** [comment]
Nice try, but let's keep it simple with everything in C. Also, we don't want to bring new dependencies in the mix. Think about future students :stuck_out_tongue:

**Comment by septatrix** [comment]
> Nice try, but let's keep it simple with everything in C. Also, we don't want to bring new dependencies in the mix. Think about future students 😛

As a potential future student I would very much appreciate Rust 😛

**Comment by LuckyTurtleDev** [comment]
> > Nice try, but let's keep it simple with everything in C. Also, we don't want to bring new dependencies in the mix. Think about future students 😛
> 
> As a potential future student I would very much appreciate Rust 😛

Same

**Comment by msrd0** [comment]
As a past student I would've liked to see the project written in Rust already

**Pull request closed without merging**
